## Configuration for online website:
baseURL = "https://applied-systems-biology.github.io/acaq5/"

## Configuration for offline website:
#uglyURLs = true

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "ACAQ5 for ImageJ"
theme = "hugo-theme-docdock"
# themesdir = "../.."
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
publishDir = "docs"
RelativeURLs=true
CanonifyURLs=true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
#
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"




[params]
editURL = ""
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fa fa-cloud-download'></i> <label>Download</label>"
url = "/download"
weight = 11

[[menu.shortcuts]]
name = "<i class='fa fa-paragraph'></i> <label>Citation</label>"
url = "/citation"
weight = 30
